kind: wasmer.io/App.v0
name: cisc3003-sugex10-path01
owner: 3357736141lym
package: .

capabilities:
  instaboot:
    requests:
      - method: GET
        path: /cisc3003-sugex10-after.php

scaling:
  mode: single_concurrency
